# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4cac124e1421cf324d1a8582fe0130487bc6095cdb5fd07a093801eb9ec9ad6c8b195eccc77cfe2df71645d670505fbe7580af30e20e712600f222458d00c1d6

test:
  secret_key_base: 63b704c97fa4338045868ed1ca7823e1d2401cf609a3eb3e1d9e11d7c431ef92df16c409784d3a33c0a985666c079b08f8f2d0782dec7e40501fdbff126dd4b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
